<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.RabbitMq" />
    <PackageReference Include="Testcontainers.Redis" />
    <PackageReference Include="Respawn" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PDR.BuildingBlocks.Core\PDR.BuildingBlocks.Core.csproj" />
    <ProjectReference Include="..\PDR.BuildingBlocks.Persistence\PDR.BuildingBlocks.Persistence.csproj" />
  </ItemGroup>

</Project>
