<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PDR.Notifications.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\BuildingBlocks\PDR.BuildingBlocks.Application\PDR.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\PDR.BuildingBlocks.Security\PDR.BuildingBlocks.Security.csproj" />
    <ProjectReference Include="..\PDR.Notifications.Domain\PDR.Notifications.Domain.csproj" />
  </ItemGroup>

</Project>
