<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PDR.BuildingBlocks.Core\PDR.BuildingBlocks.Core.csproj" />
    <ProjectReference Include="..\PDR.BuildingBlocks.Security\PDR.BuildingBlocks.Security.csproj" />
    <ProjectReference Include="..\PDR.BuildingBlocks.Observability\PDR.BuildingBlocks.Observability.csproj" />
  </ItemGroup>

</Project>
