<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\BuildingBlocks\PDR.BuildingBlocks.WebApi\PDR.BuildingBlocks.WebApi.csproj" />
    <ProjectReference Include="..\PDR.Reporting.Infrastructure\PDR.Reporting.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PDR.Reporting.IntegrationTests" />
  </ItemGroup>

</Project>
